### PR TITLE
Cool feats + factories

### PR DESCRIPTION
**Pull request by ilyabelow**
The last commits before I start writing docs and adding CI system and tests

UPD:

whoops, I accidentally integrated Travis Ci and started writing docstrings, oh well

### CODE REVIEW

**Comment by gostkin** [comment]
I suggest to use linters to validate code automatically

**Comment by gostkin** [comment]
Besides, I'd recommend to rebase branch when you are ready with pull request to remove non-informative commits. For example, if you fixed a bug/added tests/functionality then many commits with informative titles are welcomed, but several uninformative commits supposed to fix CI should be fixed up into one commit/several informative commits.

**Comment by gostkin** [comment]
Never install external packages into global scope through pip (or any other packaging system). This may cause inconsistency in dependencies and your system/some services may suddenly refuse to work. Use virtualenv instead.

**Comment by gostkin** [comment]
Put a full installation instruction and name all the dependencies your project needs in readme. If a person doesn't have pygame, then they need to google what is it and how to install (and do it securely). That's a bad option.

**Comment by gostkin** [comment]
Probably the best solution is to provide .sh script and .bat file. Keep in mind to allow script running without superuser rights (using virtualenv)

**Comment by alexeyqu** [comment]
🔥

**Pull request merged**
